spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Card
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  security: SecretKey2D3B5F2D784E6A1B423D6F242D3B5F2D784E6A1BSecret

card:
  encryption:
    key: 62ESU3kVXPXcdpcg0n6jhg==
    salt: 1961000000abcdef

redis:
  host:
    host_name: localhost:6379

logging:
  level:
    com.ed.sysbankcards: INFO