spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Card
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html